default: &default
  adapter: 'sqlite3'
  encoding: 'unicode'
  pool: 5

development:
  <<: *default
  database: 'db/development.sqlite'

production:
  <<: *default
  adapter: 'postgresql'

test:
  <<: *default
  database: 'db/test.sqlite'
