default: &default
  adapter: 'sqlite3'
  database: 'db/development.sqlite'

development:
  <<: *default

production:
  adapter: 'postgresql'
  encoding: 'unicode'
  pool: 5

test:
  <<: *default
  database: 'db/test.sqlite'
